### ISSUE TITLE
Port old fuzzing code to Go's new fuzzing tools

### ISSUE THREAD

**Issue by stv0g** [pion/sdp#148]
As introduced by Go 1.18

See: https://go.dev/security/fuzz/

**Comment by tanghaowillow** [comment]
Hi, I am new to this project. May I have a try on this? @stv0g

**Comment by stv0g** [comment]
Yes definitely! Just let me know if I can guide you or you need some other support.

**Comment by tanghaowillow** [comment]
> Yes definitely! Just let me know if I can guide you or you need some other support.

Thanks! Actually I do have several questions：
1.  I found that some of inputs generated by go-fuzzing did make sdp Unmarshaling crash which is because that the 'func (l *baseLexer) readField()' function may return empty string with a nil error.  I believe it is a bug here so am I supposed to fix it in the same PR? or I should make it a new issue?
2.  Does it also need fuzzing test for sdp marshaling? If it is needed, there are so many fields in the sdp which makes the fuzzing test needs many arguments. I couldn't find a proper way to implement it.

**Comment by stv0g** [comment]
I would do it in the same PR. Ideally in a separate commit.

And I think fuzzing is only really useful to test against maliciously crafted input data. Like SDPs received over the network.

So whenever we must process some external data..
